# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]
silent: true

tasks:
  run:
    desc: Run services
    cmds:
      - docker compose up -d
      - cd ota-orchestrator && go run ./cmd/ota-orchestrator/main.go

  stop:
    desc: Stop services
    cmds:
      - docker compose stop

  migrate:
    desc: Apply migrations
    cmds:
      - docker compose --profile migrate run --rm migrate {{.CLI_ARGS}}

  migrate-up:
    desc: Run all migrations up
    cmds:
      - task migrate -- up

  migrate-down:
    desc: Rollback one migration
    cmds:
      - task migrate -- down 1

  create-migration:
    desc: Create new migration
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.CLI_ARGS}}

  psql:
    desc: Open psql
    cmds:
      - docker compose exec -it postgres psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}}
