# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]
silent: true

vars:
  LISTPKG: '{{"{{"}}if or .TestGoFiles .XTestGoFiles{{"}}"}}{{"{{"}}.ImportPath{{"}}"}} {{"{{"}}end{{"}}"}}'

tasks:
  run-orchestrator:
    aliases:
      - ro
    desc: Run orchestrator
    cmds:
      - cd ota-orchestrator && go run ./cmd/ota-orchestrator/main.go

  run-controller:
    aliases:
      - rc
    desc: Run controller
    cmds:
      - cd rollout-controller && go run ./cmd/rollout-controller/main.go

  run-frontend:
    aliases:
      - rf
    desc: Run frontend
    cmds:
      - cd frontend && bun install && bun run gen:api && bun --bun vite dev

  run:
    desc: Run services
    cmds:
      - docker compose up -d

  stop:
    desc: Stop services
    cmds:
      - docker compose stop

  build:
    desc: Build Docker images
    cmds:
      - docker build -f ota-orchestrator/Dockerfile -t ota/ota-orchestrator .
      - docker build -f rollout-controller/Dockerfile -t ota/rollout-controller .
      - docker build -f frontend/Dockerfile -t ota/frontend .

  migrate:
    desc: Apply migrations
    cmds:
      - docker compose --profile migrate run --rm migrate {{.CLI_ARGS}}

  migrate-up:
    desc: Run all migrations up
    cmds:
      - task migrate -- up

  migrate-down:
    desc: Rollback one migration
    cmds:
      - task migrate -- down 1

  create-migration:
    desc: Create new migration
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.CLI_ARGS}}

  kafka-init:
    desc: Init kafka with topics
    cmds:
      - docker compose --profile kafka-init run --rm kafka-init

  kafka-ui:
    desc: Run docker with kafka-ui
    cmds:
      - docker compose --profile kafka-ui run --rm --service-ports kafka-ui

  psql:
    desc: Open psql
    cmds:
      - docker compose exec -it postgres psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}}

  gen:
    desc: Generate code from .proto
    cmds:
      - buf generate

  mock:
    desc: Regenerate mocks
    env:
      GOTOOLCHAIN: go1.26.0
    cmds:
      - cd ota-orchestrator && mockery
      - cd rollout-controller && mockery

  test-unit:
    aliases:
      - tu
    desc: Run unit tests in both modules
    cmds:
      - cd ota-orchestrator && gotestsum -- -race $(go list -f '{{.LISTPKG}}' ./...)
      - cd rollout-controller && gotestsum -- -race $(go list -f '{{.LISTPKG}}' ./...)

  test-all:
    aliases:
      - ta
    desc: Run all tests in both modules
    cmds:
      - cd ota-orchestrator && gotestsum -- -tags "integration,e2e" $(go list -tags "integration,e2e" -f '{{.LISTPKG}}' ./...)
      - cd rollout-controller && gotestsum -- -tags "integration,e2e" $(go list -tags "integration,e2e" -f '{{.LISTPKG}}' ./...)
