/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health */
        get: operations["checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all devices */
        get: operations["listDevices"];
        put?: never;
        /** Create a device */
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/decommission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decommission a device */
        post: operations["decommissionDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in a device */
        post: operations["checkinDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report an update attempt result */
        post: operations["reportUpdateAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all firmware versions */
        get: operations["listFirmwareVersions"];
        put?: never;
        /** Create a firmware version */
        post: operations["createFirmwareVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all rollout campaigns */
        get: operations["listRolloutCampaigns"];
        put?: never;
        /** Create a rollout campaign */
        post: operations["createRolloutCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a rollout campaign by id
         * @description Returns the campaign from Postgres. When the Rollout Controller is reachable, the response also includes live `stats` (success rate and sample size for the active stage) computed by the controller from the `firmware.update-results` stream. If the controller is unavailable, `stats` is omitted and the endpoint still returns the Postgres data.
         */
        get: operations["getRolloutCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a rollout campaign */
        post: operations["startRolloutCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a rollout campaign */
        post: operations["pauseRolloutCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a rollout campaign */
        post: operations["resumeRolloutCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force rollback a rollout campaign
         * @description Requests an administrative rollback without mutating Postgres directly. The orchestrator accepts only `running` or `paused` campaigns (for `paused` it first restores `checkin_data` of the active stage from Postgres) and then calls `CampaignService.ForceRollback` on the Rollout Controller. The controller publishes a `rollback` decision with a new `decision_id` to `rollout.decisions`; it is applied by the same consumer and status matrix as the automatic rollback. The `202` response only means the request was accepted - poll `GET /api/v1/campaigns/{id}` for the resulting `rolled_back` status. Repeating the call is safe: a new `decision_id` against an already finished campaign is a no-op on the Postgres side.
         */
        post: operations["rollbackRolloutCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example device not found */
            error: string;
        };
        ValidationErrorResponse: {
            /** @example request didn't pass validation */
            error: string;
            /**
             * @example {
             *       "current_version": "Field must be a valid semver string"
             *     }
             */
            fields: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        DeviceStatus: "active" | "decommissioned";
        DeviceResponse: {
            /** Format: uuid */
            id: string;
            device_model: string;
            current_version: string;
            status: components["schemas"]["DeviceStatus"];
            /** Format: date-time */
            last_seen?: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateDeviceRequest: {
            device_model: string;
            current_version: string;
        };
        ListDevicesResponse: {
            devices: components["schemas"]["DeviceResponse"][];
        };
        CheckinDeviceRequest: {
            current_version: string;
        };
        CheckinDeviceResponse: {
            update_available: boolean;
            /** Format: uuid */
            stage_id?: string;
            /** Format: uri */
            binary_url?: string;
            fw_checksum?: string;
        };
        /** @enum {string} */
        UpdateAttemptsResult: "success" | "failure" | "timeout";
        ReportDeviceRequest: {
            /** Format: uuid */
            campaign_id: string;
            /** Format: uuid */
            stage_id: string;
            result: components["schemas"]["UpdateAttemptsResult"];
            error_message?: string;
        };
        ReportDeviceResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            device_id: string;
            /** Format: uuid */
            campaign_id: string;
            /** Format: uuid */
            stage_id: string;
            result: components["schemas"]["UpdateAttemptsResult"];
            /** Format: date-time */
            reported_at: string;
        };
        FirmwareVersionResponse: {
            /** Format: uuid */
            id: string;
            device_model: string;
            fw_version: string;
            fw_checksum: string;
            /** Format: uri */
            binary_url: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateFirmwareVersionRequest: {
            device_model: string;
            fw_version: string;
            fw_checksum: string;
            /** Format: uri */
            binary_url: string;
        };
        ListFirmwareVersionsResponse: {
            firmware_versions: components["schemas"]["FirmwareVersionResponse"][];
        };
        /** @enum {string} */
        RolloutCampaignsStatus: "draft" | "running" | "paused" | "completed" | "rolled_back";
        /** @enum {string} */
        RolloutStagesStatus: "pending" | "active" | "passed" | "failed";
        RolloutStageRequest: {
            /** Format: int32 */
            order_index: number;
            /** Format: int32 */
            target_percent: number;
            /** Format: int32 */
            min_sample_size: number;
            /** Format: float */
            success_threshold: number;
        };
        RolloutStageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            /** Format: int32 */
            order_index: number;
            /** Format: int32 */
            target_percent: number;
            /** Format: int32 */
            min_sample_size: number;
            /** Format: float */
            success_threshold: number;
            status: components["schemas"]["RolloutStagesStatus"];
            /** Format: date-time */
            entered_at?: string;
        };
        RolloutCampaignListItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            firmware_version_id: string;
            device_model: string;
            status: components["schemas"]["RolloutCampaignsStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        RolloutCampaignResponse: components["schemas"]["RolloutCampaignListItemResponse"] & {
            rollout_stages: components["schemas"]["RolloutStageResponse"][];
            stats?: components["schemas"]["RolloutCampaignStats"];
        };
        /** @description Live rollout metrics from the Rollout Controller (Redis-based). Omitted when the controller is unavailable. */
        RolloutCampaignStats: {
            /**
             * Format: uuid
             * @description Stage currently tracked by the controller
             */
            active_stage_id: string;
            /**
             * Format: float
             * @description Share of successful update attempts in the active stage (0..1)
             */
            success_rate: number;
            /**
             * Format: int32
             * @description Total number of (deduplicated) update attempts seen for the active stage
             */
            sample_size: number;
        };
        CreateRolloutCampaignRequest: {
            /** Format: uuid */
            firmware_version_id: string;
            rollout_stages: components["schemas"]["RolloutStageRequest"][];
        };
        ListRolloutCampaignsResponse: {
            rollout_campaigns: components["schemas"]["RolloutCampaignListItemResponse"][];
        };
    };
    responses: {
        /** @description Invalid or non-valid request data */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request body exceeds the size limit (1 MiB) */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource with the given id does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with the current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Resource UUID
         * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
         */
        Id: string;
        /**
         * @description Page number (1-based). Defaults to 1 when omitted. Results are ordered newest first.
         * @example 2
         */
        Page: number;
        /**
         * @description Items per page. Defaults to the server limit (DB_PAGINATION_LIMIT) when omitted. Must not exceed the server limit.
         * @example 10
         */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        status: string;
                    };
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description Filter by device model */
                device_model?: string;
                /** @description Filter by device status */
                status?: components["schemas"]["DeviceStatus"];
                /**
                 * @description Page number (1-based). Defaults to 1 when omitted. Results are ordered newest first.
                 * @example 2
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Items per page. Defaults to the server limit (DB_PAGINATION_LIMIT) when omitted. Must not exceed the server limit.
                 * @example 10
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDevicesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description Device created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    decommissionDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device decommissioned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    checkinDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinDeviceRequest"];
            };
        };
        responses: {
            /** @description Checkin result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinDeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reportUpdateAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportDeviceRequest"];
            };
        };
        responses: {
            /** @description Update attempt recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listFirmwareVersions: {
        parameters: {
            query?: {
                /** @description Filter by device model */
                device_model?: string;
                /**
                 * @description Page number (1-based). Defaults to 1 when omitted. Results are ordered newest first.
                 * @example 2
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Items per page. Defaults to the server limit (DB_PAGINATION_LIMIT) when omitted. Must not exceed the server limit.
                 * @example 10
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of firmware versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFirmwareVersionsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createFirmwareVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFirmwareVersionRequest"];
            };
        };
        responses: {
            /** @description Firmware version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmwareVersionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listRolloutCampaigns: {
        parameters: {
            query?: {
                /**
                 * @description Page number (1-based). Defaults to 1 when omitted. Results are ordered newest first.
                 * @example 2
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Items per page. Defaults to the server limit (DB_PAGINATION_LIMIT) when omitted. Must not exceed the server limit.
                 * @example 10
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rollout campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRolloutCampaignsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRolloutCampaignRequest"];
            };
        };
        responses: {
            /** @description Rollout campaign created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutCampaignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollout campaign details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutCampaignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    startRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollout campaign started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutCampaignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    pauseRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollout campaign paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutCampaignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    resumeRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollout campaign resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutCampaignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rollbackRolloutCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resource UUID
                 * @example 3f6d2d8e-4b1c-4a5f-9a7b-8e7d1c2a3b4c
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollback request accepted, decision is applied asynchronously */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
