// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolloutCampaignRepo creates a new instance of MockRolloutCampaignRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutCampaignRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutCampaignRepo {
	mock := &MockRolloutCampaignRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolloutCampaignRepo is an autogenerated mock type for the RolloutCampaignRepo type
type MockRolloutCampaignRepo struct {
	mock.Mock
}

type MockRolloutCampaignRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutCampaignRepo) EXPECT() *MockRolloutCampaignRepo_Expecter {
	return &MockRolloutCampaignRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Get(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRolloutCampaignRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Get(ctx any, id any) *MockRolloutCampaignRepo_Get_Call {
	return &MockRolloutCampaignRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}
