// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolloutController creates a new instance of MockRolloutController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutController {
	mock := &MockRolloutController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolloutController is an autogenerated mock type for the RolloutController type
type MockRolloutController struct {
	mock.Mock
}

type MockRolloutController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutController) EXPECT() *MockRolloutController_Expecter {
	return &MockRolloutController_Expecter{mock: &_m.Mock}
}

// ForceRollback provides a mock function for the type MockRolloutController
func (_mock *MockRolloutController) ForceRollback(ctx context.Context, campaignID uuid.UUID) error {
	ret := _mock.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for ForceRollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, campaignID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRolloutController_ForceRollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceRollback'
type MockRolloutController_ForceRollback_Call struct {
	*mock.Call
}

// ForceRollback is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID uuid.UUID
func (_e *MockRolloutController_Expecter) ForceRollback(ctx any, campaignID any) *MockRolloutController_ForceRollback_Call {
	return &MockRolloutController_ForceRollback_Call{Call: _e.mock.On("ForceRollback", ctx, campaignID)}
}

func (_c *MockRolloutController_ForceRollback_Call) Run(run func(ctx context.Context, campaignID uuid.UUID)) *MockRolloutController_ForceRollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutController_ForceRollback_Call) Return(err error) *MockRolloutController_ForceRollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRolloutController_ForceRollback_Call) RunAndReturn(run func(ctx context.Context, campaignID uuid.UUID) error) *MockRolloutController_ForceRollback_Call {
	_c.Call.Return(run)
	return _c
}
