DROP TABLE IF EXISTS rollout_stages CASCADE;
DROP TABLE IF EXISTS rollout_campaigns CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS firmware_versions CASCADE;

DROP TYPE IF EXISTS DEVICE_STATUS;
DROP TYPE IF EXISTS ROLLOUT_CAMPAIGNS_STATUS;
DROP TYPE IF EXISTS ROLLOUT_STAGES_STATUS;
