dir: '{{.InterfaceDir}}/mocks'
filename: "mock_{{.InterfaceName}}.go"
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/service/campaign:
    interfaces:
      CampaignCacheRepo: {}
      FirmwareVersionRepo: {}
      RolloutCampaignRepo: {}
      RolloutController: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/service/device:
    interfaces:
      DeviceCacheRepo: {}
      DeviceRepo: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/service/firmware:
    interfaces:
      FirmwareVersionRepo: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/service/update:
    interfaces:
      CampaignCacheRepo: {}
      CheckinProducer: {}
      DeviceCacheRepo: {}
      DeviceRepo: {}
      FirmwareVersionRepo: {}
      RolloutCampaignRepo: {}
      UpdateAttemptRepo: {}
      UpdateResultsProducer: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/transport/http/handlers/device:
    interfaces:
      DeviceService: {}
      UpdateService: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/transport/http/handlers/firmware_version:
    interfaces:
      FirmwareVersionService: {}
  github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/transport/http/handlers/rollout_campaign:
    interfaces:
      RolloutCampaignService: {}
