// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFirmwareVersionRepo creates a new instance of MockFirmwareVersionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirmwareVersionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirmwareVersionRepo {
	mock := &MockFirmwareVersionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFirmwareVersionRepo is an autogenerated mock type for the FirmwareVersionRepo type
type MockFirmwareVersionRepo struct {
	mock.Mock
}

type MockFirmwareVersionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirmwareVersionRepo) EXPECT() *MockFirmwareVersionRepo_Expecter {
	return &MockFirmwareVersionRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFirmwareVersionRepo
func (_mock *MockFirmwareVersionRepo) Create(ctx context.Context, firmwareVersion domain.FirmwareVersion) (domain.FirmwareVersion, error) {
	ret := _mock.Called(ctx, firmwareVersion)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.FirmwareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) (domain.FirmwareVersion, error)); ok {
		return returnFunc(ctx, firmwareVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) domain.FirmwareVersion); ok {
		r0 = returnFunc(ctx, firmwareVersion)
	} else {
		r0 = ret.Get(0).(domain.FirmwareVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FirmwareVersion) error); ok {
		r1 = returnFunc(ctx, firmwareVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFirmwareVersionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFirmwareVersionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - firmwareVersion domain.FirmwareVersion
func (_e *MockFirmwareVersionRepo_Expecter) Create(ctx any, firmwareVersion any) *MockFirmwareVersionRepo_Create_Call {
	return &MockFirmwareVersionRepo_Create_Call{Call: _e.mock.On("Create", ctx, firmwareVersion)}
}

func (_c *MockFirmwareVersionRepo_Create_Call) Run(run func(ctx context.Context, firmwareVersion domain.FirmwareVersion)) *MockFirmwareVersionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FirmwareVersion
		if args[1] != nil {
			arg1 = args[1].(domain.FirmwareVersion)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFirmwareVersionRepo_Create_Call) Return(firmwareVersion1 domain.FirmwareVersion, err error) *MockFirmwareVersionRepo_Create_Call {
	_c.Call.Return(firmwareVersion1, err)
	return _c
}

func (_c *MockFirmwareVersionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, firmwareVersion domain.FirmwareVersion) (domain.FirmwareVersion, error)) *MockFirmwareVersionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFirmwareVersionRepo
func (_mock *MockFirmwareVersionRepo) List(ctx context.Context, deviceModel string) ([]domain.FirmwareVersion, error) {
	ret := _mock.Called(ctx, deviceModel)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.FirmwareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.FirmwareVersion, error)); ok {
		return returnFunc(ctx, deviceModel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.FirmwareVersion); ok {
		r0 = returnFunc(ctx, deviceModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FirmwareVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deviceModel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFirmwareVersionRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFirmwareVersionRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceModel string
func (_e *MockFirmwareVersionRepo_Expecter) List(ctx any, deviceModel any) *MockFirmwareVersionRepo_List_Call {
	return &MockFirmwareVersionRepo_List_Call{Call: _e.mock.On("List", ctx, deviceModel)}
}

func (_c *MockFirmwareVersionRepo_List_Call) Run(run func(ctx context.Context, deviceModel string)) *MockFirmwareVersionRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFirmwareVersionRepo_List_Call) Return(firmwareVersions []domain.FirmwareVersion, err error) *MockFirmwareVersionRepo_List_Call {
	_c.Call.Return(firmwareVersions, err)
	return _c
}

func (_c *MockFirmwareVersionRepo_List_Call) RunAndReturn(run func(ctx context.Context, deviceModel string) ([]domain.FirmwareVersion, error)) *MockFirmwareVersionRepo_List_Call {
	_c.Call.Return(run)
	return _c
}
