// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolloutCampaignRepo creates a new instance of MockRolloutCampaignRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutCampaignRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutCampaignRepo {
	mock := &MockRolloutCampaignRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolloutCampaignRepo is an autogenerated mock type for the RolloutCampaignRepo type
type MockRolloutCampaignRepo struct {
	mock.Mock
}

type MockRolloutCampaignRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutCampaignRepo) EXPECT() *MockRolloutCampaignRepo_Expecter {
	return &MockRolloutCampaignRepo_Expecter{mock: &_m.Mock}
}

// AdvanceStage provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) AdvanceStage(ctx context.Context, campaignID uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceStage")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, campaignID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, campaignID)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_AdvanceStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceStage'
type MockRolloutCampaignRepo_AdvanceStage_Call struct {
	*mock.Call
}

// AdvanceStage is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) AdvanceStage(ctx any, campaignID any) *MockRolloutCampaignRepo_AdvanceStage_Call {
	return &MockRolloutCampaignRepo_AdvanceStage_Call{Call: _e.mock.On("AdvanceStage", ctx, campaignID)}
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) Run(run func(ctx context.Context, campaignID uuid.UUID)) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) RunAndReturn(run func(ctx context.Context, campaignID uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Create(ctx context.Context, campaign domain.RolloutCampaign) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, campaign)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, campaign)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RolloutCampaign) error); ok {
		r1 = returnFunc(ctx, campaign)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRolloutCampaignRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - campaign domain.RolloutCampaign
func (_e *MockRolloutCampaignRepo_Expecter) Create(ctx any, campaign any) *MockRolloutCampaignRepo_Create_Call {
	return &MockRolloutCampaignRepo_Create_Call{Call: _e.mock.On("Create", ctx, campaign)}
}

func (_c *MockRolloutCampaignRepo_Create_Call) Run(run func(ctx context.Context, campaign domain.RolloutCampaign)) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RolloutCampaign
		if args[1] != nil {
			arg1 = args[1].(domain.RolloutCampaign)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Create_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Create_Call) RunAndReturn(run func(ctx context.Context, campaign domain.RolloutCampaign) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveStages provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) FindActiveStages(ctx context.Context, campaignIDs []uuid.UUID) ([]domain.RolloutStage, error) {
	ret := _mock.Called(ctx, campaignIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveStages")
	}

	var r0 []domain.RolloutStage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.RolloutStage, error)); ok {
		return returnFunc(ctx, campaignIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.RolloutStage); ok {
		r0 = returnFunc(ctx, campaignIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutStage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, campaignIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_FindActiveStages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveStages'
type MockRolloutCampaignRepo_FindActiveStages_Call struct {
	*mock.Call
}

// FindActiveStages is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignIDs []uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) FindActiveStages(ctx any, campaignIDs any) *MockRolloutCampaignRepo_FindActiveStages_Call {
	return &MockRolloutCampaignRepo_FindActiveStages_Call{Call: _e.mock.On("FindActiveStages", ctx, campaignIDs)}
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) Run(run func(ctx context.Context, campaignIDs []uuid.UUID)) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) Return(rolloutStages []domain.RolloutStage, err error) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Return(rolloutStages, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) RunAndReturn(run func(ctx context.Context, campaignIDs []uuid.UUID) ([]domain.RolloutStage, error)) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Get(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRolloutCampaignRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Get(ctx any, id any) *MockRolloutCampaignRepo_Get_Call {
	return &MockRolloutCampaignRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) List(ctx context.Context) ([]domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutCampaign)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRolloutCampaignRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRolloutCampaignRepo_Expecter) List(ctx any) *MockRolloutCampaignRepo_List_Call {
	return &MockRolloutCampaignRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRolloutCampaignRepo_List_Call) Run(run func(ctx context.Context)) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_List_Call) Return(rolloutCampaigns []domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Return(rolloutCampaigns, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListRunning provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) ListRunning(ctx context.Context) ([]domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRunning")
	}

	var r0 []domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutCampaign)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_ListRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRunning'
type MockRolloutCampaignRepo_ListRunning_Call struct {
	*mock.Call
}

// ListRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRolloutCampaignRepo_Expecter) ListRunning(ctx any) *MockRolloutCampaignRepo_ListRunning_Call {
	return &MockRolloutCampaignRepo_ListRunning_Call{Call: _e.mock.On("ListRunning", ctx)}
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) Run(run func(ctx context.Context)) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) Return(rolloutCampaigns []domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Return(rolloutCampaigns, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) RunAndReturn(run func(ctx context.Context) ([]domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Pause(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockRolloutCampaignRepo_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Pause(ctx any, id any) *MockRolloutCampaignRepo_Pause_Call {
	return &MockRolloutCampaignRepo_Pause_Call{Call: _e.mock.On("Pause", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Pause_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Pause_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Pause_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Resume(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockRolloutCampaignRepo_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Resume(ctx any, id any) *MockRolloutCampaignRepo_Resume_Call {
	return &MockRolloutCampaignRepo_Resume_Call{Call: _e.mock.On("Resume", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Resume_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Resume_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Resume_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockRolloutCampaignRepo
func (_mock *MockRolloutCampaignRepo) Start(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignRepo_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRolloutCampaignRepo_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Start(ctx any, id any) *MockRolloutCampaignRepo_Start_Call {
	return &MockRolloutCampaignRepo_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Start_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Start_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignRepo_Start_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Return(run)
	return _c
}
