// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRolloutCampaignRepo is an autogenerated mock type for the RolloutCampaignRepo type
type MockRolloutCampaignRepo struct {
	mock.Mock
}

type MockRolloutCampaignRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutCampaignRepo) EXPECT() *MockRolloutCampaignRepo_Expecter {
	return &MockRolloutCampaignRepo_Expecter{mock: &_m.Mock}
}

// AdvanceStage provides a mock function with given fields: ctx, campaignID
func (_m *MockRolloutCampaignRepo) AdvanceStage(ctx context.Context, campaignID uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceStage")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, campaignID)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_AdvanceStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceStage'
type MockRolloutCampaignRepo_AdvanceStage_Call struct {
	*mock.Call
}

// AdvanceStage is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) AdvanceStage(ctx interface{}, campaignID interface{}) *MockRolloutCampaignRepo_AdvanceStage_Call {
	return &MockRolloutCampaignRepo_AdvanceStage_Call{Call: _e.mock.On("AdvanceStage", ctx, campaignID)}
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) Run(run func(ctx context.Context, campaignID uuid.UUID)) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_AdvanceStage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_AdvanceStage_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRolloutCampaignRepo) Create(ctx context.Context, _a1 domain.RolloutCampaign) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) domain.RolloutCampaign); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RolloutCampaign) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRolloutCampaignRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.RolloutCampaign
func (_e *MockRolloutCampaignRepo_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRolloutCampaignRepo_Create_Call {
	return &MockRolloutCampaignRepo_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRolloutCampaignRepo_Create_Call) Run(run func(ctx context.Context, _a1 domain.RolloutCampaign)) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RolloutCampaign))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Create_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Create_Call) RunAndReturn(run func(context.Context, domain.RolloutCampaign) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveStages provides a mock function with given fields: ctx, campaignIDs
func (_m *MockRolloutCampaignRepo) FindActiveStages(ctx context.Context, campaignIDs []uuid.UUID) ([]domain.RolloutStage, error) {
	ret := _m.Called(ctx, campaignIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveStages")
	}

	var r0 []domain.RolloutStage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.RolloutStage, error)); ok {
		return rf(ctx, campaignIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.RolloutStage); ok {
		r0 = rf(ctx, campaignIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutStage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, campaignIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_FindActiveStages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveStages'
type MockRolloutCampaignRepo_FindActiveStages_Call struct {
	*mock.Call
}

// FindActiveStages is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignIDs []uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) FindActiveStages(ctx interface{}, campaignIDs interface{}) *MockRolloutCampaignRepo_FindActiveStages_Call {
	return &MockRolloutCampaignRepo_FindActiveStages_Call{Call: _e.mock.On("FindActiveStages", ctx, campaignIDs)}
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) Run(run func(ctx context.Context, campaignIDs []uuid.UUID)) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) Return(_a0 []domain.RolloutStage, _a1 error) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_FindActiveStages_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]domain.RolloutStage, error)) *MockRolloutCampaignRepo_FindActiveStages_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRolloutCampaignRepo) Get(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRolloutCampaignRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Get(ctx interface{}, id interface{}) *MockRolloutCampaignRepo_Get_Call {
	return &MockRolloutCampaignRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRolloutCampaignRepo) List(ctx context.Context) ([]domain.RolloutCampaign, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.RolloutCampaign, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.RolloutCampaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRolloutCampaignRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRolloutCampaignRepo_Expecter) List(ctx interface{}) *MockRolloutCampaignRepo_List_Call {
	return &MockRolloutCampaignRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRolloutCampaignRepo_List_Call) Run(run func(ctx context.Context)) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_List_Call) Return(_a0 []domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_List_Call) RunAndReturn(run func(context.Context) ([]domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListRunning provides a mock function with given fields: ctx
func (_m *MockRolloutCampaignRepo) ListRunning(ctx context.Context) ([]domain.RolloutCampaign, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRunning")
	}

	var r0 []domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.RolloutCampaign, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.RolloutCampaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_ListRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRunning'
type MockRolloutCampaignRepo_ListRunning_Call struct {
	*mock.Call
}

// ListRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRolloutCampaignRepo_Expecter) ListRunning(ctx interface{}) *MockRolloutCampaignRepo_ListRunning_Call {
	return &MockRolloutCampaignRepo_ListRunning_Call{Call: _e.mock.On("ListRunning", ctx)}
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) Run(run func(ctx context.Context)) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) Return(_a0 []domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_ListRunning_Call) RunAndReturn(run func(context.Context) ([]domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_ListRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function with given fields: ctx, id
func (_m *MockRolloutCampaignRepo) Pause(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockRolloutCampaignRepo_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Pause(ctx interface{}, id interface{}) *MockRolloutCampaignRepo_Pause_Call {
	return &MockRolloutCampaignRepo_Pause_Call{Call: _e.mock.On("Pause", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Pause_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Pause_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Pause_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function with given fields: ctx, id
func (_m *MockRolloutCampaignRepo) Resume(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockRolloutCampaignRepo_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Resume(ctx interface{}, id interface{}) *MockRolloutCampaignRepo_Resume_Call {
	return &MockRolloutCampaignRepo_Resume_Call{Call: _e.mock.On("Resume", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Resume_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Resume_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Resume_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, id
func (_m *MockRolloutCampaignRepo) Start(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRolloutCampaignRepo_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Start(ctx interface{}, id interface{}) *MockRolloutCampaignRepo_Start_Call {
	return &MockRolloutCampaignRepo_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Start_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Start_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Start_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRolloutCampaignRepo creates a new instance of MockRolloutCampaignRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutCampaignRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutCampaignRepo {
	mock := &MockRolloutCampaignRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
