// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRolloutController is an autogenerated mock type for the RolloutController type
type MockRolloutController struct {
	mock.Mock
}

type MockRolloutController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutController) EXPECT() *MockRolloutController_Expecter {
	return &MockRolloutController_Expecter{mock: &_m.Mock}
}

// GetCampaignStats provides a mock function with given fields: ctx, id
func (_m *MockRolloutController) GetCampaignStats(ctx context.Context, id uuid.UUID) (domain.RolloutCampaignStats, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignStats")
	}

	var r0 domain.RolloutCampaignStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaignStats, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaignStats); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaignStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutController_GetCampaignStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaignStats'
type MockRolloutController_GetCampaignStats_Call struct {
	*mock.Call
}

// GetCampaignStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutController_Expecter) GetCampaignStats(ctx interface{}, id interface{}) *MockRolloutController_GetCampaignStats_Call {
	return &MockRolloutController_GetCampaignStats_Call{Call: _e.mock.On("GetCampaignStats", ctx, id)}
}

func (_c *MockRolloutController_GetCampaignStats_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutController_GetCampaignStats_Call) Return(_a0 domain.RolloutCampaignStats, _a1 error) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutController_GetCampaignStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaignStats, error)) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRolloutController creates a new instance of MockRolloutController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutController {
	mock := &MockRolloutController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
