// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppliedDecisionRepo creates a new instance of MockAppliedDecisionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppliedDecisionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppliedDecisionRepo {
	mock := &MockAppliedDecisionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppliedDecisionRepo is an autogenerated mock type for the AppliedDecisionRepo type
type MockAppliedDecisionRepo struct {
	mock.Mock
}

type MockAppliedDecisionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppliedDecisionRepo) EXPECT() *MockAppliedDecisionRepo_Expecter {
	return &MockAppliedDecisionRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAppliedDecisionRepo
func (_mock *MockAppliedDecisionRepo) Create(ctx context.Context, decision domain.AppliedDecision) (domain.AppliedDecision, error) {
	ret := _mock.Called(ctx, decision)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.AppliedDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppliedDecision) (domain.AppliedDecision, error)); ok {
		return returnFunc(ctx, decision)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppliedDecision) domain.AppliedDecision); ok {
		r0 = returnFunc(ctx, decision)
	} else {
		r0 = ret.Get(0).(domain.AppliedDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AppliedDecision) error); ok {
		r1 = returnFunc(ctx, decision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppliedDecisionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAppliedDecisionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - decision domain.AppliedDecision
func (_e *MockAppliedDecisionRepo_Expecter) Create(ctx any, decision any) *MockAppliedDecisionRepo_Create_Call {
	return &MockAppliedDecisionRepo_Create_Call{Call: _e.mock.On("Create", ctx, decision)}
}

func (_c *MockAppliedDecisionRepo_Create_Call) Run(run func(ctx context.Context, decision domain.AppliedDecision)) *MockAppliedDecisionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AppliedDecision
		if args[1] != nil {
			arg1 = args[1].(domain.AppliedDecision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppliedDecisionRepo_Create_Call) Return(appliedDecision domain.AppliedDecision, err error) *MockAppliedDecisionRepo_Create_Call {
	_c.Call.Return(appliedDecision, err)
	return _c
}

func (_c *MockAppliedDecisionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, decision domain.AppliedDecision) (domain.AppliedDecision, error)) *MockAppliedDecisionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAppliedDecisionRepo
func (_mock *MockAppliedDecisionRepo) Get(ctx context.Context, decisionID uuid.UUID) (domain.AppliedDecision, error) {
	ret := _mock.Called(ctx, decisionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.AppliedDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.AppliedDecision, error)); ok {
		return returnFunc(ctx, decisionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.AppliedDecision); ok {
		r0 = returnFunc(ctx, decisionID)
	} else {
		r0 = ret.Get(0).(domain.AppliedDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, decisionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppliedDecisionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAppliedDecisionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - decisionID uuid.UUID
func (_e *MockAppliedDecisionRepo_Expecter) Get(ctx any, decisionID any) *MockAppliedDecisionRepo_Get_Call {
	return &MockAppliedDecisionRepo_Get_Call{Call: _e.mock.On("Get", ctx, decisionID)}
}

func (_c *MockAppliedDecisionRepo_Get_Call) Run(run func(ctx context.Context, decisionID uuid.UUID)) *MockAppliedDecisionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppliedDecisionRepo_Get_Call) Return(appliedDecision domain.AppliedDecision, err error) *MockAppliedDecisionRepo_Get_Call {
	_c.Call.Return(appliedDecision, err)
	return _c
}

func (_c *MockAppliedDecisionRepo_Get_Call) RunAndReturn(run func(ctx context.Context, decisionID uuid.UUID) (domain.AppliedDecision, error)) *MockAppliedDecisionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}
