// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStageCacheRepo creates a new instance of MockStageCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStageCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStageCacheRepo {
	mock := &MockStageCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStageCacheRepo is an autogenerated mock type for the StageCacheRepo type
type MockStageCacheRepo struct {
	mock.Mock
}

type MockStageCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStageCacheRepo) EXPECT() *MockStageCacheRepo_Expecter {
	return &MockStageCacheRepo_Expecter{mock: &_m.Mock}
}

// DeleteStageStats provides a mock function for the type MockStageCacheRepo
func (_mock *MockStageCacheRepo) DeleteStageStats(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStageStats")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageCacheRepo_DeleteStageStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStageStats'
type MockStageCacheRepo_DeleteStageStats_Call struct {
	*mock.Call
}

// DeleteStageStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStageCacheRepo_Expecter) DeleteStageStats(ctx any, id any) *MockStageCacheRepo_DeleteStageStats_Call {
	return &MockStageCacheRepo_DeleteStageStats_Call{Call: _e.mock.On("DeleteStageStats", ctx, id)}
}

func (_c *MockStageCacheRepo_DeleteStageStats_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStageCacheRepo_DeleteStageStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageCacheRepo_DeleteStageStats_Call) Return(err error) *MockStageCacheRepo_DeleteStageStats_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageCacheRepo_DeleteStageStats_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockStageCacheRepo_DeleteStageStats_Call {
	_c.Call.Return(run)
	return _c
}

// SetStageStats provides a mock function for the type MockStageCacheRepo
func (_mock *MockStageCacheRepo) SetStageStats(ctx context.Context, id uuid.UUID, stats domain.StageStats) error {
	ret := _mock.Called(ctx, id, stats)

	if len(ret) == 0 {
		panic("no return value specified for SetStageStats")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.StageStats) error); ok {
		r0 = returnFunc(ctx, id, stats)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageCacheRepo_SetStageStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStageStats'
type MockStageCacheRepo_SetStageStats_Call struct {
	*mock.Call
}

// SetStageStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - stats domain.StageStats
func (_e *MockStageCacheRepo_Expecter) SetStageStats(ctx any, id any, stats any) *MockStageCacheRepo_SetStageStats_Call {
	return &MockStageCacheRepo_SetStageStats_Call{Call: _e.mock.On("SetStageStats", ctx, id, stats)}
}

func (_c *MockStageCacheRepo_SetStageStats_Call) Run(run func(ctx context.Context, id uuid.UUID, stats domain.StageStats)) *MockStageCacheRepo_SetStageStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.StageStats
		if args[2] != nil {
			arg2 = args[2].(domain.StageStats)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageCacheRepo_SetStageStats_Call) Return(err error) *MockStageCacheRepo_SetStageStats_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageCacheRepo_SetStageStats_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, stats domain.StageStats) error) *MockStageCacheRepo_SetStageStats_Call {
	_c.Call.Return(run)
	return _c
}
