// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockCampaignCacheRepo is an autogenerated mock type for the CampaignCacheRepo type
type MockCampaignCacheRepo struct {
	mock.Mock
}

type MockCampaignCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignCacheRepo) EXPECT() *MockCampaignCacheRepo_Expecter {
	return &MockCampaignCacheRepo_Expecter{mock: &_m.Mock}
}

// DeleteCurrentStage provides a mock function with given fields: ctx, id
func (_m *MockCampaignCacheRepo) DeleteCurrentStage(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCurrentStage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignCacheRepo_DeleteCurrentStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCurrentStage'
type MockCampaignCacheRepo_DeleteCurrentStage_Call struct {
	*mock.Call
}

// DeleteCurrentStage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) DeleteCurrentStage(ctx interface{}, id interface{}) *MockCampaignCacheRepo_DeleteCurrentStage_Call {
	return &MockCampaignCacheRepo_DeleteCurrentStage_Call{Call: _e.mock.On("DeleteCurrentStage", ctx, id)}
}

func (_c *MockCampaignCacheRepo_DeleteCurrentStage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignCacheRepo_DeleteCurrentStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCampaignCacheRepo_DeleteCurrentStage_Call) Return(_a0 error) *MockCampaignCacheRepo_DeleteCurrentStage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignCacheRepo_DeleteCurrentStage_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCampaignCacheRepo_DeleteCurrentStage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCurrentTargetPercent provides a mock function with given fields: ctx, id
func (_m *MockCampaignCacheRepo) DeleteCurrentTargetPercent(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCurrentTargetPercent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCurrentTargetPercent'
type MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call struct {
	*mock.Call
}

// DeleteCurrentTargetPercent is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) DeleteCurrentTargetPercent(ctx interface{}, id interface{}) *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call {
	return &MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call{Call: _e.mock.On("DeleteCurrentTargetPercent", ctx, id)}
}

func (_c *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call) Return(_a0 error) *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCampaignCacheRepo_DeleteCurrentTargetPercent_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrentStage provides a mock function with given fields: ctx, id, stageID
func (_m *MockCampaignCacheRepo) SetCurrentStage(ctx context.Context, id uuid.UUID, stageID uuid.UUID) error {
	ret := _m.Called(ctx, id, stageID)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentStage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, stageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignCacheRepo_SetCurrentStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentStage'
type MockCampaignCacheRepo_SetCurrentStage_Call struct {
	*mock.Call
}

// SetCurrentStage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - stageID uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) SetCurrentStage(ctx interface{}, id interface{}, stageID interface{}) *MockCampaignCacheRepo_SetCurrentStage_Call {
	return &MockCampaignCacheRepo_SetCurrentStage_Call{Call: _e.mock.On("SetCurrentStage", ctx, id, stageID)}
}

func (_c *MockCampaignCacheRepo_SetCurrentStage_Call) Run(run func(ctx context.Context, id uuid.UUID, stageID uuid.UUID)) *MockCampaignCacheRepo_SetCurrentStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCampaignCacheRepo_SetCurrentStage_Call) Return(_a0 error) *MockCampaignCacheRepo_SetCurrentStage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignCacheRepo_SetCurrentStage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCampaignCacheRepo_SetCurrentStage_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrentTargetPercent provides a mock function with given fields: ctx, id, percent
func (_m *MockCampaignCacheRepo) SetCurrentTargetPercent(ctx context.Context, id uuid.UUID, percent int) error {
	ret := _m.Called(ctx, id, percent)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentTargetPercent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, id, percent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignCacheRepo_SetCurrentTargetPercent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentTargetPercent'
type MockCampaignCacheRepo_SetCurrentTargetPercent_Call struct {
	*mock.Call
}

// SetCurrentTargetPercent is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - percent int
func (_e *MockCampaignCacheRepo_Expecter) SetCurrentTargetPercent(ctx interface{}, id interface{}, percent interface{}) *MockCampaignCacheRepo_SetCurrentTargetPercent_Call {
	return &MockCampaignCacheRepo_SetCurrentTargetPercent_Call{Call: _e.mock.On("SetCurrentTargetPercent", ctx, id, percent)}
}

func (_c *MockCampaignCacheRepo_SetCurrentTargetPercent_Call) Run(run func(ctx context.Context, id uuid.UUID, percent int)) *MockCampaignCacheRepo_SetCurrentTargetPercent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockCampaignCacheRepo_SetCurrentTargetPercent_Call) Return(_a0 error) *MockCampaignCacheRepo_SetCurrentTargetPercent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignCacheRepo_SetCurrentTargetPercent_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *MockCampaignCacheRepo_SetCurrentTargetPercent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCampaignCacheRepo creates a new instance of MockCampaignCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignCacheRepo {
	mock := &MockCampaignCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
