// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFirmwareVersionRepo is an autogenerated mock type for the FirmwareVersionRepo type
type MockFirmwareVersionRepo struct {
	mock.Mock
}

type MockFirmwareVersionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirmwareVersionRepo) EXPECT() *MockFirmwareVersionRepo_Expecter {
	return &MockFirmwareVersionRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockFirmwareVersionRepo) Get(ctx context.Context, id uuid.UUID) (domain.FirmwareVersion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.FirmwareVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.FirmwareVersion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.FirmwareVersion); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.FirmwareVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFirmwareVersionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFirmwareVersionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFirmwareVersionRepo_Expecter) Get(ctx interface{}, id interface{}) *MockFirmwareVersionRepo_Get_Call {
	return &MockFirmwareVersionRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockFirmwareVersionRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFirmwareVersionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFirmwareVersionRepo_Get_Call) Return(_a0 domain.FirmwareVersion, _a1 error) *MockFirmwareVersionRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFirmwareVersionRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.FirmwareVersion, error)) *MockFirmwareVersionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFirmwareVersionRepo creates a new instance of MockFirmwareVersionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirmwareVersionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirmwareVersionRepo {
	mock := &MockFirmwareVersionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
