// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolloutController creates a new instance of MockRolloutController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutController {
	mock := &MockRolloutController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolloutController is an autogenerated mock type for the RolloutController type
type MockRolloutController struct {
	mock.Mock
}

type MockRolloutController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutController) EXPECT() *MockRolloutController_Expecter {
	return &MockRolloutController_Expecter{mock: &_m.Mock}
}

// GetCampaignStats provides a mock function for the type MockRolloutController
func (_mock *MockRolloutController) GetCampaignStats(ctx context.Context, id uuid.UUID) (domain.RolloutCampaignStats, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignStats")
	}

	var r0 domain.RolloutCampaignStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaignStats, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaignStats); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaignStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutController_GetCampaignStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaignStats'
type MockRolloutController_GetCampaignStats_Call struct {
	*mock.Call
}

// GetCampaignStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutController_Expecter) GetCampaignStats(ctx any, id any) *MockRolloutController_GetCampaignStats_Call {
	return &MockRolloutController_GetCampaignStats_Call{Call: _e.mock.On("GetCampaignStats", ctx, id)}
}

func (_c *MockRolloutController_GetCampaignStats_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutController_GetCampaignStats_Call) Return(rolloutCampaignStats domain.RolloutCampaignStats, err error) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Return(rolloutCampaignStats, err)
	return _c
}

func (_c *MockRolloutController_GetCampaignStats_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaignStats, error)) *MockRolloutController_GetCampaignStats_Call {
	_c.Call.Return(run)
	return _c
}
