// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateAttemptRepo creates a new instance of MockUpdateAttemptRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateAttemptRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateAttemptRepo {
	mock := &MockUpdateAttemptRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateAttemptRepo is an autogenerated mock type for the UpdateAttemptRepo type
type MockUpdateAttemptRepo struct {
	mock.Mock
}

type MockUpdateAttemptRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateAttemptRepo) EXPECT() *MockUpdateAttemptRepo_Expecter {
	return &MockUpdateAttemptRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUpdateAttemptRepo
func (_mock *MockUpdateAttemptRepo) Create(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error) {
	ret := _mock.Called(ctx, updateAttempt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.UpdateAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)); ok {
		return returnFunc(ctx, updateAttempt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) domain.UpdateAttempt); ok {
		r0 = returnFunc(ctx, updateAttempt)
	} else {
		r0 = ret.Get(0).(domain.UpdateAttempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UpdateAttempt) error); ok {
		r1 = returnFunc(ctx, updateAttempt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateAttemptRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUpdateAttemptRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - updateAttempt domain.UpdateAttempt
func (_e *MockUpdateAttemptRepo_Expecter) Create(ctx any, updateAttempt any) *MockUpdateAttemptRepo_Create_Call {
	return &MockUpdateAttemptRepo_Create_Call{Call: _e.mock.On("Create", ctx, updateAttempt)}
}

func (_c *MockUpdateAttemptRepo_Create_Call) Run(run func(ctx context.Context, updateAttempt domain.UpdateAttempt)) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UpdateAttempt
		if args[1] != nil {
			arg1 = args[1].(domain.UpdateAttempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateAttemptRepo_Create_Call) Return(updateAttempt1 domain.UpdateAttempt, err error) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Return(updateAttempt1, err)
	return _c
}

func (_c *MockUpdateAttemptRepo_Create_Call) RunAndReturn(run func(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error)) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}
