// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCampaignCacheRepo creates a new instance of MockCampaignCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignCacheRepo {
	mock := &MockCampaignCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCampaignCacheRepo is an autogenerated mock type for the CampaignCacheRepo type
type MockCampaignCacheRepo struct {
	mock.Mock
}

type MockCampaignCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignCacheRepo) EXPECT() *MockCampaignCacheRepo_Expecter {
	return &MockCampaignCacheRepo_Expecter{mock: &_m.Mock}
}

// GetCurrentStage provides a mock function for the type MockCampaignCacheRepo
func (_mock *MockCampaignCacheRepo) GetCurrentStage(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentStage")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCampaignCacheRepo_GetCurrentStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentStage'
type MockCampaignCacheRepo_GetCurrentStage_Call struct {
	*mock.Call
}

// GetCurrentStage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) GetCurrentStage(ctx any, id any) *MockCampaignCacheRepo_GetCurrentStage_Call {
	return &MockCampaignCacheRepo_GetCurrentStage_Call{Call: _e.mock.On("GetCurrentStage", ctx, id)}
}

func (_c *MockCampaignCacheRepo_GetCurrentStage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignCacheRepo_GetCurrentStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCampaignCacheRepo_GetCurrentStage_Call) Return(uUID uuid.UUID, err error) *MockCampaignCacheRepo_GetCurrentStage_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockCampaignCacheRepo_GetCurrentStage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (uuid.UUID, error)) *MockCampaignCacheRepo_GetCurrentStage_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentTargetPercent provides a mock function for the type MockCampaignCacheRepo
func (_mock *MockCampaignCacheRepo) GetCurrentTargetPercent(ctx context.Context, id uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentTargetPercent")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCampaignCacheRepo_GetCurrentTargetPercent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentTargetPercent'
type MockCampaignCacheRepo_GetCurrentTargetPercent_Call struct {
	*mock.Call
}

// GetCurrentTargetPercent is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) GetCurrentTargetPercent(ctx any, id any) *MockCampaignCacheRepo_GetCurrentTargetPercent_Call {
	return &MockCampaignCacheRepo_GetCurrentTargetPercent_Call{Call: _e.mock.On("GetCurrentTargetPercent", ctx, id)}
}

func (_c *MockCampaignCacheRepo_GetCurrentTargetPercent_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignCacheRepo_GetCurrentTargetPercent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCampaignCacheRepo_GetCurrentTargetPercent_Call) Return(n int, err error) *MockCampaignCacheRepo_GetCurrentTargetPercent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCampaignCacheRepo_GetCurrentTargetPercent_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (int, error)) *MockCampaignCacheRepo_GetCurrentTargetPercent_Call {
	_c.Call.Return(run)
	return _c
}
