// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeviceRepo is an autogenerated mock type for the DeviceRepo type
type MockDeviceRepo struct {
	mock.Mock
}

type MockDeviceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepo) EXPECT() *MockDeviceRepo_Expecter {
	return &MockDeviceRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockDeviceRepo) Get(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Device, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Device); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeviceRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepo_Expecter) Get(ctx interface{}, id interface{}) *MockDeviceRepo_Get_Call {
	return &MockDeviceRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockDeviceRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceRepo_Get_Call) Return(_a0 domain.Device, _a1 error) *MockDeviceRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.Device, error)) *MockDeviceRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceRepo creates a new instance of MockDeviceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepo {
	mock := &MockDeviceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
