// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceRepo creates a new instance of MockDeviceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepo {
	mock := &MockDeviceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceRepo is an autogenerated mock type for the DeviceRepo type
type MockDeviceRepo struct {
	mock.Mock
}

type MockDeviceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepo) EXPECT() *MockDeviceRepo_Expecter {
	return &MockDeviceRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) Get(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Device, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Device); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeviceRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepo_Expecter) Get(ctx any, id any) *MockDeviceRepo_Get_Call {
	return &MockDeviceRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockDeviceRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_Get_Call) Return(device domain.Device, err error) *MockDeviceRepo_Get_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Device, error)) *MockDeviceRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}
