// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceCacheRepo creates a new instance of MockDeviceCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceCacheRepo {
	mock := &MockDeviceCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceCacheRepo is an autogenerated mock type for the DeviceCacheRepo type
type MockDeviceCacheRepo struct {
	mock.Mock
}

type MockDeviceCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceCacheRepo) EXPECT() *MockDeviceCacheRepo_Expecter {
	return &MockDeviceCacheRepo_Expecter{mock: &_m.Mock}
}

// SetCheckinData provides a mock function for the type MockDeviceCacheRepo
func (_mock *MockDeviceCacheRepo) SetCheckinData(ctx context.Context, id uuid.UUID, data domain.DeviceCheckinData) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for SetCheckinData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.DeviceCheckinData) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceCacheRepo_SetCheckinData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCheckinData'
type MockDeviceCacheRepo_SetCheckinData_Call struct {
	*mock.Call
}

// SetCheckinData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - data domain.DeviceCheckinData
func (_e *MockDeviceCacheRepo_Expecter) SetCheckinData(ctx any, id any, data any) *MockDeviceCacheRepo_SetCheckinData_Call {
	return &MockDeviceCacheRepo_SetCheckinData_Call{Call: _e.mock.On("SetCheckinData", ctx, id, data)}
}

func (_c *MockDeviceCacheRepo_SetCheckinData_Call) Run(run func(ctx context.Context, id uuid.UUID, data domain.DeviceCheckinData)) *MockDeviceCacheRepo_SetCheckinData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.DeviceCheckinData
		if args[2] != nil {
			arg2 = args[2].(domain.DeviceCheckinData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceCacheRepo_SetCheckinData_Call) Return(err error) *MockDeviceCacheRepo_SetCheckinData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceCacheRepo_SetCheckinData_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, data domain.DeviceCheckinData) error) *MockDeviceCacheRepo_SetCheckinData_Call {
	_c.Call.Return(run)
	return _c
}
