// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeviceCacheRepo is an autogenerated mock type for the DeviceCacheRepo type
type MockDeviceCacheRepo struct {
	mock.Mock
}

type MockDeviceCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceCacheRepo) EXPECT() *MockDeviceCacheRepo_Expecter {
	return &MockDeviceCacheRepo_Expecter{mock: &_m.Mock}
}

// SetCurrentVersion provides a mock function with given fields: ctx, id, currentVersion
func (_m *MockDeviceCacheRepo) SetCurrentVersion(ctx context.Context, id uuid.UUID, currentVersion string) error {
	ret := _m.Called(ctx, id, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, currentVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceCacheRepo_SetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentVersion'
type MockDeviceCacheRepo_SetCurrentVersion_Call struct {
	*mock.Call
}

// SetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - currentVersion string
func (_e *MockDeviceCacheRepo_Expecter) SetCurrentVersion(ctx interface{}, id interface{}, currentVersion interface{}) *MockDeviceCacheRepo_SetCurrentVersion_Call {
	return &MockDeviceCacheRepo_SetCurrentVersion_Call{Call: _e.mock.On("SetCurrentVersion", ctx, id, currentVersion)}
}

func (_c *MockDeviceCacheRepo_SetCurrentVersion_Call) Run(run func(ctx context.Context, id uuid.UUID, currentVersion string)) *MockDeviceCacheRepo_SetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockDeviceCacheRepo_SetCurrentVersion_Call) Return(_a0 error) *MockDeviceCacheRepo_SetCurrentVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceCacheRepo_SetCurrentVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockDeviceCacheRepo_SetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastSeen provides a mock function with given fields: ctx, id, lastSeen
func (_m *MockDeviceCacheRepo) SetLastSeen(ctx context.Context, id uuid.UUID, lastSeen time.Time) error {
	ret := _m.Called(ctx, id, lastSeen)

	if len(ret) == 0 {
		panic("no return value specified for SetLastSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, lastSeen)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceCacheRepo_SetLastSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastSeen'
type MockDeviceCacheRepo_SetLastSeen_Call struct {
	*mock.Call
}

// SetLastSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - lastSeen time.Time
func (_e *MockDeviceCacheRepo_Expecter) SetLastSeen(ctx interface{}, id interface{}, lastSeen interface{}) *MockDeviceCacheRepo_SetLastSeen_Call {
	return &MockDeviceCacheRepo_SetLastSeen_Call{Call: _e.mock.On("SetLastSeen", ctx, id, lastSeen)}
}

func (_c *MockDeviceCacheRepo_SetLastSeen_Call) Run(run func(ctx context.Context, id uuid.UUID, lastSeen time.Time)) *MockDeviceCacheRepo_SetLastSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDeviceCacheRepo_SetLastSeen_Call) Return(_a0 error) *MockDeviceCacheRepo_SetLastSeen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceCacheRepo_SetLastSeen_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockDeviceCacheRepo_SetLastSeen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceCacheRepo creates a new instance of MockDeviceCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceCacheRepo {
	mock := &MockDeviceCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
