// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateResultsProducer creates a new instance of MockUpdateResultsProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateResultsProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateResultsProducer {
	mock := &MockUpdateResultsProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateResultsProducer is an autogenerated mock type for the UpdateResultsProducer type
type MockUpdateResultsProducer struct {
	mock.Mock
}

type MockUpdateResultsProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateResultsProducer) EXPECT() *MockUpdateResultsProducer_Expecter {
	return &MockUpdateResultsProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockUpdateResultsProducer
func (_mock *MockUpdateResultsProducer) Produce(event domain.UpdateResultsEvent) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.UpdateResultsEvent) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdateResultsProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockUpdateResultsProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - event domain.UpdateResultsEvent
func (_e *MockUpdateResultsProducer_Expecter) Produce(event any) *MockUpdateResultsProducer_Produce_Call {
	return &MockUpdateResultsProducer_Produce_Call{Call: _e.mock.On("Produce", event)}
}

func (_c *MockUpdateResultsProducer_Produce_Call) Run(run func(event domain.UpdateResultsEvent)) *MockUpdateResultsProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.UpdateResultsEvent
		if args[0] != nil {
			arg0 = args[0].(domain.UpdateResultsEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdateResultsProducer_Produce_Call) Return(err error) *MockUpdateResultsProducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdateResultsProducer_Produce_Call) RunAndReturn(run func(event domain.UpdateResultsEvent) error) *MockUpdateResultsProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}
