// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCampaignCacheRepo creates a new instance of MockCampaignCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignCacheRepo {
	mock := &MockCampaignCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCampaignCacheRepo is an autogenerated mock type for the CampaignCacheRepo type
type MockCampaignCacheRepo struct {
	mock.Mock
}

type MockCampaignCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignCacheRepo) EXPECT() *MockCampaignCacheRepo_Expecter {
	return &MockCampaignCacheRepo_Expecter{mock: &_m.Mock}
}

// GetCheckinData provides a mock function for the type MockCampaignCacheRepo
func (_mock *MockCampaignCacheRepo) GetCheckinData(ctx context.Context, id uuid.UUID) (domain.CampaignCheckinData, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckinData")
	}

	var r0 domain.CampaignCheckinData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.CampaignCheckinData, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.CampaignCheckinData); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.CampaignCheckinData)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCampaignCacheRepo_GetCheckinData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckinData'
type MockCampaignCacheRepo_GetCheckinData_Call struct {
	*mock.Call
}

// GetCheckinData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignCacheRepo_Expecter) GetCheckinData(ctx any, id any) *MockCampaignCacheRepo_GetCheckinData_Call {
	return &MockCampaignCacheRepo_GetCheckinData_Call{Call: _e.mock.On("GetCheckinData", ctx, id)}
}

func (_c *MockCampaignCacheRepo_GetCheckinData_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignCacheRepo_GetCheckinData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCampaignCacheRepo_GetCheckinData_Call) Return(campaignCheckinData domain.CampaignCheckinData, err error) *MockCampaignCacheRepo_GetCheckinData_Call {
	_c.Call.Return(campaignCheckinData, err)
	return _c
}

func (_c *MockCampaignCacheRepo_GetCheckinData_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.CampaignCheckinData, error)) *MockCampaignCacheRepo_GetCheckinData_Call {
	_c.Call.Return(run)
	return _c
}
