// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckinProducer creates a new instance of MockCheckinProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckinProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckinProducer {
	mock := &MockCheckinProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckinProducer is an autogenerated mock type for the CheckinProducer type
type MockCheckinProducer struct {
	mock.Mock
}

type MockCheckinProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckinProducer) EXPECT() *MockCheckinProducer_Expecter {
	return &MockCheckinProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockCheckinProducer
func (_mock *MockCheckinProducer) Produce(event domain.CheckinEvent) {
	_mock.Called(event)
	return
}

// MockCheckinProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockCheckinProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - event domain.CheckinEvent
func (_e *MockCheckinProducer_Expecter) Produce(event any) *MockCheckinProducer_Produce_Call {
	return &MockCheckinProducer_Produce_Call{Call: _e.mock.On("Produce", event)}
}

func (_c *MockCheckinProducer_Produce_Call) Run(run func(event domain.CheckinEvent)) *MockCheckinProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.CheckinEvent
		if args[0] != nil {
			arg0 = args[0].(domain.CheckinEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckinProducer_Produce_Call) Return() *MockCheckinProducer_Produce_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckinProducer_Produce_Call) RunAndReturn(run func(event domain.CheckinEvent)) *MockCheckinProducer_Produce_Call {
	_c.Run(run)
	return _c
}
