// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateAttemptRepo is an autogenerated mock type for the UpdateAttemptRepo type
type MockUpdateAttemptRepo struct {
	mock.Mock
}

type MockUpdateAttemptRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateAttemptRepo) EXPECT() *MockUpdateAttemptRepo_Expecter {
	return &MockUpdateAttemptRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, updateAttempt
func (_m *MockUpdateAttemptRepo) Create(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error) {
	ret := _m.Called(ctx, updateAttempt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.UpdateAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)); ok {
		return rf(ctx, updateAttempt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) domain.UpdateAttempt); ok {
		r0 = rf(ctx, updateAttempt)
	} else {
		r0 = ret.Get(0).(domain.UpdateAttempt)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateAttempt) error); ok {
		r1 = rf(ctx, updateAttempt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateAttemptRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUpdateAttemptRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - updateAttempt domain.UpdateAttempt
func (_e *MockUpdateAttemptRepo_Expecter) Create(ctx interface{}, updateAttempt interface{}) *MockUpdateAttemptRepo_Create_Call {
	return &MockUpdateAttemptRepo_Create_Call{Call: _e.mock.On("Create", ctx, updateAttempt)}
}

func (_c *MockUpdateAttemptRepo_Create_Call) Run(run func(ctx context.Context, updateAttempt domain.UpdateAttempt)) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UpdateAttempt))
	})
	return _c
}

func (_c *MockUpdateAttemptRepo_Create_Call) Return(_a0 domain.UpdateAttempt, _a1 error) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateAttemptRepo_Create_Call) RunAndReturn(run func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)) *MockUpdateAttemptRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateAttemptRepo creates a new instance of MockUpdateAttemptRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateAttemptRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateAttemptRepo {
	mock := &MockUpdateAttemptRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
