// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRolloutCampaignRepo is an autogenerated mock type for the RolloutCampaignRepo type
type MockRolloutCampaignRepo struct {
	mock.Mock
}

type MockRolloutCampaignRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutCampaignRepo) EXPECT() *MockRolloutCampaignRepo_Expecter {
	return &MockRolloutCampaignRepo_Expecter{mock: &_m.Mock}
}

// FindRunning provides a mock function with given fields: ctx, deviceModel
func (_m *MockRolloutCampaignRepo) FindRunning(ctx context.Context, deviceModel string) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, deviceModel)

	if len(ret) == 0 {
		panic("no return value specified for FindRunning")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, deviceModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.RolloutCampaign); ok {
		r0 = rf(ctx, deviceModel)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_FindRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRunning'
type MockRolloutCampaignRepo_FindRunning_Call struct {
	*mock.Call
}

// FindRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceModel string
func (_e *MockRolloutCampaignRepo_Expecter) FindRunning(ctx interface{}, deviceModel interface{}) *MockRolloutCampaignRepo_FindRunning_Call {
	return &MockRolloutCampaignRepo_FindRunning_Call{Call: _e.mock.On("FindRunning", ctx, deviceModel)}
}

func (_c *MockRolloutCampaignRepo_FindRunning_Call) Run(run func(ctx context.Context, deviceModel string)) *MockRolloutCampaignRepo_FindRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_FindRunning_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_FindRunning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_FindRunning_Call) RunAndReturn(run func(context.Context, string) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_FindRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRolloutCampaignRepo) Get(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolloutCampaignRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRolloutCampaignRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignRepo_Expecter) Get(ctx interface{}, id interface{}) *MockRolloutCampaignRepo_Get_Call {
	return &MockRolloutCampaignRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRolloutCampaignRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) Return(_a0 domain.RolloutCampaign, _a1 error) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolloutCampaignRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRolloutCampaignRepo creates a new instance of MockRolloutCampaignRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutCampaignRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutCampaignRepo {
	mock := &MockRolloutCampaignRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
