// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFirmwareVersionService creates a new instance of MockFirmwareVersionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirmwareVersionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirmwareVersionService {
	mock := &MockFirmwareVersionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFirmwareVersionService is an autogenerated mock type for the FirmwareVersionService type
type MockFirmwareVersionService struct {
	mock.Mock
}

type MockFirmwareVersionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirmwareVersionService) EXPECT() *MockFirmwareVersionService_Expecter {
	return &MockFirmwareVersionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFirmwareVersionService
func (_mock *MockFirmwareVersionService) Create(ctx context.Context, firmwareVersion domain.FirmwareVersion) (domain.FirmwareVersion, error) {
	ret := _mock.Called(ctx, firmwareVersion)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.FirmwareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) (domain.FirmwareVersion, error)); ok {
		return returnFunc(ctx, firmwareVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) domain.FirmwareVersion); ok {
		r0 = returnFunc(ctx, firmwareVersion)
	} else {
		r0 = ret.Get(0).(domain.FirmwareVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FirmwareVersion) error); ok {
		r1 = returnFunc(ctx, firmwareVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFirmwareVersionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFirmwareVersionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - firmwareVersion domain.FirmwareVersion
func (_e *MockFirmwareVersionService_Expecter) Create(ctx any, firmwareVersion any) *MockFirmwareVersionService_Create_Call {
	return &MockFirmwareVersionService_Create_Call{Call: _e.mock.On("Create", ctx, firmwareVersion)}
}

func (_c *MockFirmwareVersionService_Create_Call) Run(run func(ctx context.Context, firmwareVersion domain.FirmwareVersion)) *MockFirmwareVersionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FirmwareVersion
		if args[1] != nil {
			arg1 = args[1].(domain.FirmwareVersion)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFirmwareVersionService_Create_Call) Return(firmwareVersion1 domain.FirmwareVersion, err error) *MockFirmwareVersionService_Create_Call {
	_c.Call.Return(firmwareVersion1, err)
	return _c
}

func (_c *MockFirmwareVersionService_Create_Call) RunAndReturn(run func(ctx context.Context, firmwareVersion domain.FirmwareVersion) (domain.FirmwareVersion, error)) *MockFirmwareVersionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFirmwareVersionService
func (_mock *MockFirmwareVersionService) List(ctx context.Context, deviceModel string, pagination domain.Pagination) ([]domain.FirmwareVersion, error) {
	ret := _mock.Called(ctx, deviceModel, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.FirmwareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Pagination) ([]domain.FirmwareVersion, error)); ok {
		return returnFunc(ctx, deviceModel, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Pagination) []domain.FirmwareVersion); ok {
		r0 = returnFunc(ctx, deviceModel, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FirmwareVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Pagination) error); ok {
		r1 = returnFunc(ctx, deviceModel, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFirmwareVersionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFirmwareVersionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceModel string
//   - pagination domain.Pagination
func (_e *MockFirmwareVersionService_Expecter) List(ctx any, deviceModel any, pagination any) *MockFirmwareVersionService_List_Call {
	return &MockFirmwareVersionService_List_Call{Call: _e.mock.On("List", ctx, deviceModel, pagination)}
}

func (_c *MockFirmwareVersionService_List_Call) Run(run func(ctx context.Context, deviceModel string, pagination domain.Pagination)) *MockFirmwareVersionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Pagination
		if args[2] != nil {
			arg2 = args[2].(domain.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFirmwareVersionService_List_Call) Return(firmwareVersions []domain.FirmwareVersion, err error) *MockFirmwareVersionService_List_Call {
	_c.Call.Return(firmwareVersions, err)
	return _c
}

func (_c *MockFirmwareVersionService_List_Call) RunAndReturn(run func(ctx context.Context, deviceModel string, pagination domain.Pagination) ([]domain.FirmwareVersion, error)) *MockFirmwareVersionService_List_Call {
	_c.Call.Return(run)
	return _c
}
