// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFirmwareVersionService is an autogenerated mock type for the FirmwareVersionService type
type MockFirmwareVersionService struct {
	mock.Mock
}

type MockFirmwareVersionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirmwareVersionService) EXPECT() *MockFirmwareVersionService_Expecter {
	return &MockFirmwareVersionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, firmwareVersion
func (_m *MockFirmwareVersionService) Create(ctx context.Context, firmwareVersion domain.FirmwareVersion) (domain.FirmwareVersion, error) {
	ret := _m.Called(ctx, firmwareVersion)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.FirmwareVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) (domain.FirmwareVersion, error)); ok {
		return rf(ctx, firmwareVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.FirmwareVersion) domain.FirmwareVersion); ok {
		r0 = rf(ctx, firmwareVersion)
	} else {
		r0 = ret.Get(0).(domain.FirmwareVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.FirmwareVersion) error); ok {
		r1 = rf(ctx, firmwareVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFirmwareVersionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFirmwareVersionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - firmwareVersion domain.FirmwareVersion
func (_e *MockFirmwareVersionService_Expecter) Create(ctx interface{}, firmwareVersion interface{}) *MockFirmwareVersionService_Create_Call {
	return &MockFirmwareVersionService_Create_Call{Call: _e.mock.On("Create", ctx, firmwareVersion)}
}

func (_c *MockFirmwareVersionService_Create_Call) Run(run func(ctx context.Context, firmwareVersion domain.FirmwareVersion)) *MockFirmwareVersionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.FirmwareVersion))
	})
	return _c
}

func (_c *MockFirmwareVersionService_Create_Call) Return(_a0 domain.FirmwareVersion, _a1 error) *MockFirmwareVersionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFirmwareVersionService_Create_Call) RunAndReturn(run func(context.Context, domain.FirmwareVersion) (domain.FirmwareVersion, error)) *MockFirmwareVersionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockFirmwareVersionService) List(ctx context.Context) ([]domain.FirmwareVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.FirmwareVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.FirmwareVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.FirmwareVersion); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FirmwareVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFirmwareVersionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFirmwareVersionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFirmwareVersionService_Expecter) List(ctx interface{}) *MockFirmwareVersionService_List_Call {
	return &MockFirmwareVersionService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockFirmwareVersionService_List_Call) Run(run func(ctx context.Context)) *MockFirmwareVersionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFirmwareVersionService_List_Call) Return(_a0 []domain.FirmwareVersion, _a1 error) *MockFirmwareVersionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFirmwareVersionService_List_Call) RunAndReturn(run func(context.Context) ([]domain.FirmwareVersion, error)) *MockFirmwareVersionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFirmwareVersionService creates a new instance of MockFirmwareVersionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirmwareVersionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirmwareVersionService {
	mock := &MockFirmwareVersionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
