// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/rollout-controller/internal/core/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCampaignStatsService is an autogenerated mock type for the CampaignStatsService type
type MockCampaignStatsService struct {
	mock.Mock
}

type MockCampaignStatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignStatsService) EXPECT() *MockCampaignStatsService_Expecter {
	return &MockCampaignStatsService_Expecter{mock: &_m.Mock}
}

// GetCampaignStats provides a mock function with given fields: ctx, id
func (_m *MockCampaignStatsService) GetCampaignStats(ctx context.Context, id uuid.UUID) (domain.CampaignStats, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignStats")
	}

	var r0 domain.CampaignStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.CampaignStats, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.CampaignStats); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.CampaignStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCampaignStatsService_GetCampaignStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaignStats'
type MockCampaignStatsService_GetCampaignStats_Call struct {
	*mock.Call
}

// GetCampaignStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignStatsService_Expecter) GetCampaignStats(ctx interface{}, id interface{}) *MockCampaignStatsService_GetCampaignStats_Call {
	return &MockCampaignStatsService_GetCampaignStats_Call{Call: _e.mock.On("GetCampaignStats", ctx, id)}
}

func (_c *MockCampaignStatsService_GetCampaignStats_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignStatsService_GetCampaignStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCampaignStatsService_GetCampaignStats_Call) Return(_a0 domain.CampaignStats, _a1 error) *MockCampaignStatsService_GetCampaignStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCampaignStatsService_GetCampaignStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.CampaignStats, error)) *MockCampaignStatsService_GetCampaignStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCampaignStatsService creates a new instance of MockCampaignStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignStatsService {
	mock := &MockCampaignStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
