// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/rollout-controller/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDecisionsService creates a new instance of MockDecisionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecisionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecisionsService {
	mock := &MockDecisionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDecisionsService is an autogenerated mock type for the DecisionsService type
type MockDecisionsService struct {
	mock.Mock
}

type MockDecisionsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecisionsService) EXPECT() *MockDecisionsService_Expecter {
	return &MockDecisionsService_Expecter{mock: &_m.Mock}
}

// SendDecision provides a mock function for the type MockDecisionsService
func (_mock *MockDecisionsService) SendDecision(ctx context.Context, campaignID uuid.UUID, decision domain.DecisionType) error {
	ret := _mock.Called(ctx, campaignID, decision)

	if len(ret) == 0 {
		panic("no return value specified for SendDecision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.DecisionType) error); ok {
		r0 = returnFunc(ctx, campaignID, decision)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDecisionsService_SendDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDecision'
type MockDecisionsService_SendDecision_Call struct {
	*mock.Call
}

// SendDecision is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID uuid.UUID
//   - decision domain.DecisionType
func (_e *MockDecisionsService_Expecter) SendDecision(ctx any, campaignID any, decision any) *MockDecisionsService_SendDecision_Call {
	return &MockDecisionsService_SendDecision_Call{Call: _e.mock.On("SendDecision", ctx, campaignID, decision)}
}

func (_c *MockDecisionsService_SendDecision_Call) Run(run func(ctx context.Context, campaignID uuid.UUID, decision domain.DecisionType)) *MockDecisionsService_SendDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.DecisionType
		if args[2] != nil {
			arg2 = args[2].(domain.DecisionType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDecisionsService_SendDecision_Call) Return(err error) *MockDecisionsService_SendDecision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDecisionsService_SendDecision_Call) RunAndReturn(run func(ctx context.Context, campaignID uuid.UUID, decision domain.DecisionType) error) *MockDecisionsService_SendDecision_Call {
	_c.Call.Return(run)
	return _c
}
