// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceRepo creates a new instance of MockDeviceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepo {
	mock := &MockDeviceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceRepo is an autogenerated mock type for the DeviceRepo type
type MockDeviceRepo struct {
	mock.Mock
}

type MockDeviceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepo) EXPECT() *MockDeviceRepo_Expecter {
	return &MockDeviceRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) Create(ctx context.Context, device domain.Device) (domain.Device, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) (domain.Device, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) domain.Device); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Device) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeviceRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - device domain.Device
func (_e *MockDeviceRepo_Expecter) Create(ctx any, device any) *MockDeviceRepo_Create_Call {
	return &MockDeviceRepo_Create_Call{Call: _e.mock.On("Create", ctx, device)}
}

func (_c *MockDeviceRepo_Create_Call) Run(run func(ctx context.Context, device domain.Device)) *MockDeviceRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Device
		if args[1] != nil {
			arg1 = args[1].(domain.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_Create_Call) Return(device1 domain.Device, err error) *MockDeviceRepo_Create_Call {
	_c.Call.Return(device1, err)
	return _c
}

func (_c *MockDeviceRepo_Create_Call) RunAndReturn(run func(ctx context.Context, device domain.Device) (domain.Device, error)) *MockDeviceRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decommission provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) Decommission(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Decommission")
	}

	var r0 domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Device, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Device); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepo_Decommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decommission'
type MockDeviceRepo_Decommission_Call struct {
	*mock.Call
}

// Decommission is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepo_Expecter) Decommission(ctx any, id any) *MockDeviceRepo_Decommission_Call {
	return &MockDeviceRepo_Decommission_Call{Call: _e.mock.On("Decommission", ctx, id)}
}

func (_c *MockDeviceRepo_Decommission_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepo_Decommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_Decommission_Call) Return(device domain.Device, err error) *MockDeviceRepo_Decommission_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceRepo_Decommission_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Device, error)) *MockDeviceRepo_Decommission_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) List(ctx context.Context) ([]domain.Device, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Device, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Device); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeviceRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeviceRepo_Expecter) List(ctx any) *MockDeviceRepo_List_Call {
	return &MockDeviceRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDeviceRepo_List_Call) Run(run func(ctx context.Context)) *MockDeviceRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_List_Call) Return(devices []domain.Device, err error) *MockDeviceRepo_List_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockDeviceRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Device, error)) *MockDeviceRepo_List_Call {
	_c.Call.Return(run)
	return _c
}
