// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockDeviceCacheRepo is an autogenerated mock type for the DeviceCacheRepo type
type MockDeviceCacheRepo struct {
	mock.Mock
}

type MockDeviceCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceCacheRepo) EXPECT() *MockDeviceCacheRepo_Expecter {
	return &MockDeviceCacheRepo_Expecter{mock: &_m.Mock}
}

// GetCurrentVersion provides a mock function with given fields: ctx, id
func (_m *MockDeviceCacheRepo) GetCurrentVersion(ctx context.Context, id uuid.UUID) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceCacheRepo_GetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentVersion'
type MockDeviceCacheRepo_GetCurrentVersion_Call struct {
	*mock.Call
}

// GetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceCacheRepo_Expecter) GetCurrentVersion(ctx interface{}, id interface{}) *MockDeviceCacheRepo_GetCurrentVersion_Call {
	return &MockDeviceCacheRepo_GetCurrentVersion_Call{Call: _e.mock.On("GetCurrentVersion", ctx, id)}
}

func (_c *MockDeviceCacheRepo_GetCurrentVersion_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceCacheRepo_GetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceCacheRepo_GetCurrentVersion_Call) Return(_a0 string, _a1 error) *MockDeviceCacheRepo_GetCurrentVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceCacheRepo_GetCurrentVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *MockDeviceCacheRepo_GetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSeen provides a mock function with given fields: ctx, id
func (_m *MockDeviceCacheRepo) GetLastSeen(ctx context.Context, id uuid.UUID) (time.Time, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSeen")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (time.Time, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) time.Time); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceCacheRepo_GetLastSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSeen'
type MockDeviceCacheRepo_GetLastSeen_Call struct {
	*mock.Call
}

// GetLastSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceCacheRepo_Expecter) GetLastSeen(ctx interface{}, id interface{}) *MockDeviceCacheRepo_GetLastSeen_Call {
	return &MockDeviceCacheRepo_GetLastSeen_Call{Call: _e.mock.On("GetLastSeen", ctx, id)}
}

func (_c *MockDeviceCacheRepo_GetLastSeen_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceCacheRepo_GetLastSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceCacheRepo_GetLastSeen_Call) Return(_a0 time.Time, _a1 error) *MockDeviceCacheRepo_GetLastSeen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceCacheRepo_GetLastSeen_Call) RunAndReturn(run func(context.Context, uuid.UUID) (time.Time, error)) *MockDeviceCacheRepo_GetLastSeen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceCacheRepo creates a new instance of MockDeviceCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceCacheRepo {
	mock := &MockDeviceCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
