// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeviceRepo is an autogenerated mock type for the DeviceRepo type
type MockDeviceRepo struct {
	mock.Mock
}

type MockDeviceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepo) EXPECT() *MockDeviceRepo_Expecter {
	return &MockDeviceRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockDeviceRepo) Create(ctx context.Context, _a1 domain.Device) (domain.Device, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Device) (domain.Device, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Device) domain.Device); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Device) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeviceRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.Device
func (_e *MockDeviceRepo_Expecter) Create(ctx interface{}, _a1 interface{}) *MockDeviceRepo_Create_Call {
	return &MockDeviceRepo_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockDeviceRepo_Create_Call) Run(run func(ctx context.Context, _a1 domain.Device)) *MockDeviceRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Device))
	})
	return _c
}

func (_c *MockDeviceRepo_Create_Call) Return(_a0 domain.Device, _a1 error) *MockDeviceRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepo_Create_Call) RunAndReturn(run func(context.Context, domain.Device) (domain.Device, error)) *MockDeviceRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decommission provides a mock function with given fields: ctx, id
func (_m *MockDeviceRepo) Decommission(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Decommission")
	}

	var r0 domain.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Device, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Device); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepo_Decommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decommission'
type MockDeviceRepo_Decommission_Call struct {
	*mock.Call
}

// Decommission is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepo_Expecter) Decommission(ctx interface{}, id interface{}) *MockDeviceRepo_Decommission_Call {
	return &MockDeviceRepo_Decommission_Call{Call: _e.mock.On("Decommission", ctx, id)}
}

func (_c *MockDeviceRepo_Decommission_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepo_Decommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceRepo_Decommission_Call) Return(_a0 domain.Device, _a1 error) *MockDeviceRepo_Decommission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepo_Decommission_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.Device, error)) *MockDeviceRepo_Decommission_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockDeviceRepo) List(ctx context.Context) ([]domain.Device, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Device, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Device); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeviceRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeviceRepo_Expecter) List(ctx interface{}) *MockDeviceRepo_List_Call {
	return &MockDeviceRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDeviceRepo_List_Call) Run(run func(ctx context.Context)) *MockDeviceRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDeviceRepo_List_Call) Return(_a0 []domain.Device, _a1 error) *MockDeviceRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepo_List_Call) RunAndReturn(run func(context.Context) ([]domain.Device, error)) *MockDeviceRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceRepo creates a new instance of MockDeviceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepo {
	mock := &MockDeviceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
