// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceCacheRepo creates a new instance of MockDeviceCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceCacheRepo {
	mock := &MockDeviceCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceCacheRepo is an autogenerated mock type for the DeviceCacheRepo type
type MockDeviceCacheRepo struct {
	mock.Mock
}

type MockDeviceCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceCacheRepo) EXPECT() *MockDeviceCacheRepo_Expecter {
	return &MockDeviceCacheRepo_Expecter{mock: &_m.Mock}
}

// ListDeviceCheckinData provides a mock function for the type MockDeviceCacheRepo
func (_mock *MockDeviceCacheRepo) ListDeviceCheckinData(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]string, map[uuid.UUID]time.Time, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListDeviceCheckinData")
	}

	var r0 map[uuid.UUID]string
	var r1 map[uuid.UUID]time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]string, map[uuid.UUID]time.Time, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]string); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) map[uuid.UUID]time.Time); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[uuid.UUID]time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []uuid.UUID) error); ok {
		r2 = returnFunc(ctx, ids)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeviceCacheRepo_ListDeviceCheckinData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeviceCheckinData'
type MockDeviceCacheRepo_ListDeviceCheckinData_Call struct {
	*mock.Call
}

// ListDeviceCheckinData is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockDeviceCacheRepo_Expecter) ListDeviceCheckinData(ctx any, ids any) *MockDeviceCacheRepo_ListDeviceCheckinData_Call {
	return &MockDeviceCacheRepo_ListDeviceCheckinData_Call{Call: _e.mock.On("ListDeviceCheckinData", ctx, ids)}
}

func (_c *MockDeviceCacheRepo_ListDeviceCheckinData_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockDeviceCacheRepo_ListDeviceCheckinData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceCacheRepo_ListDeviceCheckinData_Call) Return(versions map[uuid.UUID]string, lastSeen map[uuid.UUID]time.Time, err error) *MockDeviceCacheRepo_ListDeviceCheckinData_Call {
	_c.Call.Return(versions, lastSeen, err)
	return _c
}

func (_c *MockDeviceCacheRepo_ListDeviceCheckinData_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]string, map[uuid.UUID]time.Time, error)) *MockDeviceCacheRepo_ListDeviceCheckinData_Call {
	_c.Call.Return(run)
	return _c
}
