// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceService creates a new instance of MockDeviceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceService {
	mock := &MockDeviceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceService is an autogenerated mock type for the DeviceService type
type MockDeviceService struct {
	mock.Mock
}

type MockDeviceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceService) EXPECT() *MockDeviceService_Expecter {
	return &MockDeviceService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) Create(ctx context.Context, device domain.Device) (domain.Device, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) (domain.Device, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) domain.Device); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Device) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeviceService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - device domain.Device
func (_e *MockDeviceService_Expecter) Create(ctx any, device any) *MockDeviceService_Create_Call {
	return &MockDeviceService_Create_Call{Call: _e.mock.On("Create", ctx, device)}
}

func (_c *MockDeviceService_Create_Call) Run(run func(ctx context.Context, device domain.Device)) *MockDeviceService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Device
		if args[1] != nil {
			arg1 = args[1].(domain.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceService_Create_Call) Return(device1 domain.Device, err error) *MockDeviceService_Create_Call {
	_c.Call.Return(device1, err)
	return _c
}

func (_c *MockDeviceService_Create_Call) RunAndReturn(run func(ctx context.Context, device domain.Device) (domain.Device, error)) *MockDeviceService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decommission provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) Decommission(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Decommission")
	}

	var r0 domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Device, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Device); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_Decommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decommission'
type MockDeviceService_Decommission_Call struct {
	*mock.Call
}

// Decommission is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceService_Expecter) Decommission(ctx any, id any) *MockDeviceService_Decommission_Call {
	return &MockDeviceService_Decommission_Call{Call: _e.mock.On("Decommission", ctx, id)}
}

func (_c *MockDeviceService_Decommission_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceService_Decommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceService_Decommission_Call) Return(device domain.Device, err error) *MockDeviceService_Decommission_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_Decommission_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Device, error)) *MockDeviceService_Decommission_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) List(ctx context.Context, filters domain.DeviceFilters) ([]domain.Device, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DeviceFilters) ([]domain.Device, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DeviceFilters) []domain.Device); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DeviceFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeviceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters domain.DeviceFilters
func (_e *MockDeviceService_Expecter) List(ctx any, filters any) *MockDeviceService_List_Call {
	return &MockDeviceService_List_Call{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockDeviceService_List_Call) Run(run func(ctx context.Context, filters domain.DeviceFilters)) *MockDeviceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DeviceFilters
		if args[1] != nil {
			arg1 = args[1].(domain.DeviceFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceService_List_Call) Return(devices []domain.Device, err error) *MockDeviceService_List_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockDeviceService_List_Call) RunAndReturn(run func(ctx context.Context, filters domain.DeviceFilters) ([]domain.Device, error)) *MockDeviceService_List_Call {
	_c.Call.Return(run)
	return _c
}
