// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateService creates a new instance of MockUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateService {
	mock := &MockUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateService is an autogenerated mock type for the UpdateService type
type MockUpdateService struct {
	mock.Mock
}

type MockUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateService) EXPECT() *MockUpdateService_Expecter {
	return &MockUpdateService_Expecter{mock: &_m.Mock}
}

// Checkin provides a mock function for the type MockUpdateService
func (_mock *MockUpdateService) Checkin(ctx context.Context, device domain.Device) (domain.CheckinResult, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Checkin")
	}

	var r0 domain.CheckinResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) (domain.CheckinResult, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Device) domain.CheckinResult); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(domain.CheckinResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Device) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateService_Checkin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkin'
type MockUpdateService_Checkin_Call struct {
	*mock.Call
}

// Checkin is a helper method to define mock.On call
//   - ctx context.Context
//   - device domain.Device
func (_e *MockUpdateService_Expecter) Checkin(ctx any, device any) *MockUpdateService_Checkin_Call {
	return &MockUpdateService_Checkin_Call{Call: _e.mock.On("Checkin", ctx, device)}
}

func (_c *MockUpdateService_Checkin_Call) Run(run func(ctx context.Context, device domain.Device)) *MockUpdateService_Checkin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Device
		if args[1] != nil {
			arg1 = args[1].(domain.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateService_Checkin_Call) Return(checkinResult domain.CheckinResult, err error) *MockUpdateService_Checkin_Call {
	_c.Call.Return(checkinResult, err)
	return _c
}

func (_c *MockUpdateService_Checkin_Call) RunAndReturn(run func(ctx context.Context, device domain.Device) (domain.CheckinResult, error)) *MockUpdateService_Checkin_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function for the type MockUpdateService
func (_mock *MockUpdateService) Report(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error) {
	ret := _mock.Called(ctx, updateAttempt)

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 domain.UpdateAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)); ok {
		return returnFunc(ctx, updateAttempt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) domain.UpdateAttempt); ok {
		r0 = returnFunc(ctx, updateAttempt)
	} else {
		r0 = ret.Get(0).(domain.UpdateAttempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UpdateAttempt) error); ok {
		r1 = returnFunc(ctx, updateAttempt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateService_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockUpdateService_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - ctx context.Context
//   - updateAttempt domain.UpdateAttempt
func (_e *MockUpdateService_Expecter) Report(ctx any, updateAttempt any) *MockUpdateService_Report_Call {
	return &MockUpdateService_Report_Call{Call: _e.mock.On("Report", ctx, updateAttempt)}
}

func (_c *MockUpdateService_Report_Call) Run(run func(ctx context.Context, updateAttempt domain.UpdateAttempt)) *MockUpdateService_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UpdateAttempt
		if args[1] != nil {
			arg1 = args[1].(domain.UpdateAttempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateService_Report_Call) Return(updateAttempt1 domain.UpdateAttempt, err error) *MockUpdateService_Report_Call {
	_c.Call.Return(updateAttempt1, err)
	return _c
}

func (_c *MockUpdateService_Report_Call) RunAndReturn(run func(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error)) *MockUpdateService_Report_Call {
	_c.Call.Return(run)
	return _c
}
