// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateService is an autogenerated mock type for the UpdateService type
type MockUpdateService struct {
	mock.Mock
}

type MockUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateService) EXPECT() *MockUpdateService_Expecter {
	return &MockUpdateService_Expecter{mock: &_m.Mock}
}

// Checkin provides a mock function with given fields: ctx, _a1
func (_m *MockUpdateService) Checkin(ctx context.Context, _a1 domain.Device) (domain.CheckinResult, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Checkin")
	}

	var r0 domain.CheckinResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Device) (domain.CheckinResult, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Device) domain.CheckinResult); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.CheckinResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Device) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateService_Checkin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkin'
type MockUpdateService_Checkin_Call struct {
	*mock.Call
}

// Checkin is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.Device
func (_e *MockUpdateService_Expecter) Checkin(ctx interface{}, _a1 interface{}) *MockUpdateService_Checkin_Call {
	return &MockUpdateService_Checkin_Call{Call: _e.mock.On("Checkin", ctx, _a1)}
}

func (_c *MockUpdateService_Checkin_Call) Run(run func(ctx context.Context, _a1 domain.Device)) *MockUpdateService_Checkin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Device))
	})
	return _c
}

func (_c *MockUpdateService_Checkin_Call) Return(_a0 domain.CheckinResult, _a1 error) *MockUpdateService_Checkin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateService_Checkin_Call) RunAndReturn(run func(context.Context, domain.Device) (domain.CheckinResult, error)) *MockUpdateService_Checkin_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function with given fields: ctx, updateAttempt
func (_m *MockUpdateService) Report(ctx context.Context, updateAttempt domain.UpdateAttempt) (domain.UpdateAttempt, error) {
	ret := _m.Called(ctx, updateAttempt)

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 domain.UpdateAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)); ok {
		return rf(ctx, updateAttempt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateAttempt) domain.UpdateAttempt); ok {
		r0 = rf(ctx, updateAttempt)
	} else {
		r0 = ret.Get(0).(domain.UpdateAttempt)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateAttempt) error); ok {
		r1 = rf(ctx, updateAttempt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateService_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockUpdateService_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - ctx context.Context
//   - updateAttempt domain.UpdateAttempt
func (_e *MockUpdateService_Expecter) Report(ctx interface{}, updateAttempt interface{}) *MockUpdateService_Report_Call {
	return &MockUpdateService_Report_Call{Call: _e.mock.On("Report", ctx, updateAttempt)}
}

func (_c *MockUpdateService_Report_Call) Run(run func(ctx context.Context, updateAttempt domain.UpdateAttempt)) *MockUpdateService_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UpdateAttempt))
	})
	return _c
}

func (_c *MockUpdateService_Report_Call) Return(_a0 domain.UpdateAttempt, _a1 error) *MockUpdateService_Report_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateService_Report_Call) RunAndReturn(run func(context.Context, domain.UpdateAttempt) (domain.UpdateAttempt, error)) *MockUpdateService_Report_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateService creates a new instance of MockUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateService {
	mock := &MockUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
