// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arondy/OTA-Firmware-Orchestrator/ota-orchestrator/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolloutCampaignService creates a new instance of MockRolloutCampaignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolloutCampaignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolloutCampaignService {
	mock := &MockRolloutCampaignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolloutCampaignService is an autogenerated mock type for the RolloutCampaignService type
type MockRolloutCampaignService struct {
	mock.Mock
}

type MockRolloutCampaignService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolloutCampaignService) EXPECT() *MockRolloutCampaignService_Expecter {
	return &MockRolloutCampaignService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) Create(ctx context.Context, campaign domain.RolloutCampaign) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, campaign)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RolloutCampaign) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, campaign)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RolloutCampaign) error); ok {
		r1 = returnFunc(ctx, campaign)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRolloutCampaignService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - campaign domain.RolloutCampaign
func (_e *MockRolloutCampaignService_Expecter) Create(ctx any, campaign any) *MockRolloutCampaignService_Create_Call {
	return &MockRolloutCampaignService_Create_Call{Call: _e.mock.On("Create", ctx, campaign)}
}

func (_c *MockRolloutCampaignService_Create_Call) Run(run func(ctx context.Context, campaign domain.RolloutCampaign)) *MockRolloutCampaignService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RolloutCampaign
		if args[1] != nil {
			arg1 = args[1].(domain.RolloutCampaign)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_Create_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignService_Create_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignService_Create_Call) RunAndReturn(run func(ctx context.Context, campaign domain.RolloutCampaign) (domain.RolloutCampaign, error)) *MockRolloutCampaignService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) Get(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRolloutCampaignService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignService_Expecter) Get(ctx any, id any) *MockRolloutCampaignService_Get_Call {
	return &MockRolloutCampaignService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRolloutCampaignService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_Get_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignService_Get_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignService_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) List(ctx context.Context, pagination domain.Pagination) ([]domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Pagination) ([]domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Pagination) []domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolloutCampaign)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Pagination) error); ok {
		r1 = returnFunc(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRolloutCampaignService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination domain.Pagination
func (_e *MockRolloutCampaignService_Expecter) List(ctx any, pagination any) *MockRolloutCampaignService_List_Call {
	return &MockRolloutCampaignService_List_Call{Call: _e.mock.On("List", ctx, pagination)}
}

func (_c *MockRolloutCampaignService_List_Call) Run(run func(ctx context.Context, pagination domain.Pagination)) *MockRolloutCampaignService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Pagination
		if args[1] != nil {
			arg1 = args[1].(domain.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_List_Call) Return(rolloutCampaigns []domain.RolloutCampaign, err error) *MockRolloutCampaignService_List_Call {
	_c.Call.Return(rolloutCampaigns, err)
	return _c
}

func (_c *MockRolloutCampaignService_List_Call) RunAndReturn(run func(ctx context.Context, pagination domain.Pagination) ([]domain.RolloutCampaign, error)) *MockRolloutCampaignService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) Pause(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockRolloutCampaignService_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignService_Expecter) Pause(ctx any, id any) *MockRolloutCampaignService_Pause_Call {
	return &MockRolloutCampaignService_Pause_Call{Call: _e.mock.On("Pause", ctx, id)}
}

func (_c *MockRolloutCampaignService_Pause_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignService_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_Pause_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignService_Pause_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignService_Pause_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignService_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) Resume(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockRolloutCampaignService_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignService_Expecter) Resume(ctx any, id any) *MockRolloutCampaignService_Resume_Call {
	return &MockRolloutCampaignService_Resume_Call{Call: _e.mock.On("Resume", ctx, id)}
}

func (_c *MockRolloutCampaignService_Resume_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignService_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_Resume_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignService_Resume_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignService_Resume_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignService_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockRolloutCampaignService
func (_mock *MockRolloutCampaignService) Start(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 domain.RolloutCampaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.RolloutCampaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.RolloutCampaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.RolloutCampaign)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolloutCampaignService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRolloutCampaignService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRolloutCampaignService_Expecter) Start(ctx any, id any) *MockRolloutCampaignService_Start_Call {
	return &MockRolloutCampaignService_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockRolloutCampaignService_Start_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRolloutCampaignService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolloutCampaignService_Start_Call) Return(rolloutCampaign domain.RolloutCampaign, err error) *MockRolloutCampaignService_Start_Call {
	_c.Call.Return(rolloutCampaign, err)
	return _c
}

func (_c *MockRolloutCampaignService_Start_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.RolloutCampaign, error)) *MockRolloutCampaignService_Start_Call {
	_c.Call.Return(run)
	return _c
}
